name: release

on:
  push:
    tags: 
      - 'v*'

env:
  REGISTRY: ghcr.io
  MOVIES_IMAGE_NAME: 'cinema-movies'

jobs:
  multi-registries:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      # setups
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        
      # build and push each microservice release 
      - name: Build and push movies microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./movies/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./movies/Dockerfile
          tags: |
            mikebellcoder/${{ env.MOVIES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mikebellcoder/${{ env.MOVIES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
