name: release

on:
  push:
    tags:
      - "v*"

env:
  BOOKINGS_IMAGE_NAME: "cinema-bookings"
  MOVIES_IMAGE_NAME: "cinema-movies"
  SHOWTIMES_IMAGE_NAME: "cinema-showtimes"
  USERS_IMAGE_NAME: "cinema-users"
  WEBSITE_IMAGE_NAME: "cinema-website"

jobs:
  multi-registries:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # setups
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_2 }}
          password: ${{ secrets.DOCKERHUB_TOKEN_2 }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      # bookings microservice
      - name: Build and push bookings microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./bookings
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./bookings/Dockerfile
          tags: |
            mikebellcoder/${{ env.BOOKINGS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mikebellcoder/${{ env.BOOKINGS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      # movies microservice
      - name: Build and push movies microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./movies/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./movies/Dockerfile
          tags: |
            mikebellcoder/${{ env.MOVIES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mikebellcoder/${{ env.MOVIES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      # showtimes microservice
      - name: Build and push showtimes microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./showtimes/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./showtimes/Dockerfile
          tags: |
            mikebellcoder/${{ env.SHOWTIMES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mikebellcoder/${{ env.SHOWTIMES_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      # users microservice
      - name: Build and push users microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./users/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./users/Dockerfile
          tags: |
            mikebellcoder/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} 
            ghcr.io/mikebellcoder/${{ env.USERS_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      # website microservice
      - name: Build and push website microservice
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./website/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./website/Dockerfile
          tags: |
            mikebellcoder/${{ env.WEBSITE_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mikebellcoder/${{ env.WEBSITE_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
